# Generated by Django 5.1.15 on 2026-06-20 19:11

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.CharField(default=core.models._uuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('finance', 'finance'), ('procurement', 'procurement'), ('viewer', 'viewer')], default='viewer', max_length=20)),
                ('status', models.CharField(choices=[('active', 'active'), ('disabled', 'disabled'), ('invited', 'invited')], default='active', max_length=20)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.CharField(default=core.models._uuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('client_id', models.CharField(blank=True, max_length=64, null=True)),
                ('user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('action', models.CharField(max_length=80)),
                ('entity', models.CharField(blank=True, max_length=80, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=64, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.CharField(default=core.models._uuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(blank=True, max_length=120, null=True)),
                ('category', models.CharField(blank=True, max_length=80, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('terms', models.TextField(blank=True, null=True)),
                ('default_discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('status', models.CharField(default='active', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('denominations', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(default=core.models._uuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=200, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('allow_wallet', models.BooleanField(default=True)),
                ('allow_bank_transfer', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginOtp',
            fields=[
                ('id', models.CharField(default=core.models._uuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('otp_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('consumed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('value', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lines', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='core.appuser')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='core.client')),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.client'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=core.models._uuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(default='pending_payment', max_length=24)),
                ('total_face_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_quantity', models.IntegerField(default=0)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_status', models.CharField(default='unpaid', max_length=24)),
                ('payment_proof_url', models.CharField(blank=True, max_length=500, null=True)),
                ('utr_number', models.CharField(blank=True, max_length=40, null=True)),
                ('payment_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('payment_verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=64, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=300, null=True)),
                ('placed_by_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.appuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadToken',
            fields=[
                ('id', models.CharField(default=core.models._uuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=80, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('otp_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.CharField(default=core.models._uuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('brand_id', models.CharField(max_length=64)),
                ('brand_name', models.CharField(max_length=200)),
                ('brand_logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('denomination', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('face_value_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.CharField(default=core.models._uuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('order_item_id', models.CharField(blank=True, max_length=64, null=True)),
                ('brand_id', models.CharField(blank=True, max_length=64, null=True)),
                ('brand_name', models.CharField(max_length=200)),
                ('denomination', models.IntegerField()),
                ('code', models.CharField(max_length=80)),
                ('pin', models.CharField(blank=True, max_length=20, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='issued', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='core.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.CharField(default=core.models._uuid, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('credit', 'credit'), ('debit', 'debit'), ('refund', 'refund')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_txns', to='core.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ratecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratecards', to='core.brand')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratecards', to='core.client')),
            ],
            options={
                'unique_together': {('client', 'brand')},
            },
        ),
    ]
